apiVersion: v1
kind: Secret
metadata:
  name: webhook-secret
  namespace: tekton-trigger-demo
stringData:
  token: <GITHUB_ACCESS_TOKEN>
  secret: random-string-data
---
apiVersion: v1
data:
  .dockerconfigjson: <DOCKER_CONFIG>
kind: Secret
metadata:
  name: tgillson-registry
  namespace: tekton-trigger-demo
type: kubernetes.io/dockerconfigjson
