version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - cyclop
    - gocognit
    - asciicheck
    - gocritic
    - makezero
    - nakedret
    - nilerr
    - nolintlint
    - misspell
    - whitespace
    - mnd

  settings:
    errcheck:
      exclude-functions:
        - (*github.com/hashicorp/terraform-plugin-framework/tfsdk.State).SetAttribute
    gocognit:
      min-complexity: 158
    cyclop:
      max-complexity: 100
      package-average: 16.0 
    staticcheck:
      checks:
        - "-QF1001"
    gocritic:
      enabled-tags:
        - diagnostic
      disabled-tags:
        - style
        - performance
        - experimental
        - opinionated
    mnd:
      checks:
        - case
        - operation
        - return
      ignored-functions:
        - os.Exit
        - stringvalidator.LengthAtMost
        - stringvalidator.LengthBetween
    nolintlint:
      allow-unused: false
      allow-no-explanation:
        - mnd
  exclusions:
    rules:
      - path: (.+)_test\.go
        linters:
          - errcheck
          - gosimple
          - ineffassign
          - staticcheck
          - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0


run:
  timeout: 10m