# References:
# - https://golangci-lint.run/usage/linters/

run:
  timeout: 10m # default 1m

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment # too strict
      - shadow # too strict

  # Non-default
  cyclop:
    # Top 3:
    # (*SpectroClusterReconciler).reconcileOnPilot: 80
    # (*SpectroClusterReconciler).reconcilePacks: 65
    # clusterdeployer (*manager).Reconcile: 52
    max-complexity: 80 # maximal code complexity to report; default 10
    package-average: 16.0 # maximal average package complexity to report; default 0.0
  gocognit:
    # Top 3:
    # (*SpectroClusterReconciler).reconcileOnPilot: 158
    # (*SpectroClusterReconciler).reconcilePacks: 136
    # clusterdeployer (*manager).Reconcile: 107
    min-complexity: 158 # minimal code complexity to report; default: 30

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - cyclop
    - gocognit

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosimple
        - ineffassign
        - staticcheck
        - unused