# # References:
# # - https://golangci-lint.run/usage/linters/
# version: "2"
# run:
#   timeout: 10m # default 1m

# # linters-settings:
# #   govet:
# #     enable-all: true
# #     disable:
# #       - fieldalignment # too strict
# #       - shadow # too strict






version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - cyclop
    - gocognit
    - asciicheck
    - gocritic
    - makezero
    - nakedret
    - nilerr
    - nolintlint
    # - misspell
    # - mnd
    # - unconvert
    # - unparam
    # - whitespace
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/hashicorp/terraform-plugin-framework/tfsdk.State).SetAttribute
    gocognit:
      min-complexity: 120
    cyclop:
      max-complexity: 100
      package-average: 16.0 
    # staticcheck:
    #   checks:
    #     - SA1019
    gocritic:
      enabled-tags:
        - diagnostic
      disabled-tags:
        - style
        - performance
        - experimental
        - opinionated
    mnd:
      checks:
        - argument
        - assign
        - case
        - operation
        - return
      ignored-functions:
        - os.Exit
        - stringvalidator.LengthAtMost
        - stringvalidator.LengthBetween
    nolintlint:
      allow-unused: false
      allow-no-explanation:
        - mnd
    unparam:
      check-exported: true
  exclusions:
    rules:
      - path: (.+)_test\.go
        linters:
          - errcheck
          - gosimple
          - ineffassign
          - staticcheck
          - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0


run:
  timeout: 10m