repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.11.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-generate
