---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
  name: ${WORKER_NODE_POOL_NAME}
spec:
  clusterName: ${CLUSTER_NAME}
  replicas: ${WORKER_NODE_SIZE}
  selector:
    matchLabels: {}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: worker-pool-resource
      clusterName: ${CLUSTER_NAME}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: NutanixMachineTemplate
        name: worker-pool-resource
      version: ${KUBERNETES_VERSION}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: NutanixMachineTemplate
metadata:
  name: worker-pool-resource
spec:
  template:
    spec:
      bootType: ${NUTANIX_MACHINE_BOOT_TYPE}
      cluster:
        name: ${NUTANIX_PRISM_ELEMENT_CLUSTER_NAME}
        type: name
      image:
        name: ${NUTANIX_MACHINE_TEMPLATE_IMAGE_NAME}
        type: name
      memorySize: ${NUTANIX_MACHINE_MEMORY_SIZE}
      providerID: nutanix://${CLUSTER_NAME}-mt-0
      subnet:
        - name: ${NUTANIX_SUBNET_NAME}
          type: name
      systemDiskSize: ${NUTANIX_SYSTEMDISK_SIZE}
      vcpuSockets: ${NUTANIX_MACHINE_VCPU_SOCKET}
      vcpusPerSocket: ${NUTANIX_MACHINE_VCPU_PER_SOCKET}

---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: worker-pool-resource
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            eviction-hard: nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<15%,memory.available<100Mi,imagefs.inodesFree<10%
            tls-cipher-suites: ${TLS_CIPHER_SUITES}
      postKubeadmCommands:
        - echo "after kubeadm call" > /var/log/postkubeadm.log
      preKubeadmCommands:
        - echo "before kubeadm call" > /var/log/prekubeadm.log
        - hostnamectl set-hostname "{{ ds.meta_data.hostname }}"
      users:
        - lockPassword: false
          name: capiuser
          sshAuthorizedKeys:
            - ${NUTANIX_SSH_AUTHORIZED_KEY}
          sudo: ALL=(ALL) NOPASSWD:ALL
      verbosity: 10
---


